### ISSUE TITLE
[question] `biome.js` on vs `.biome.json`

### ISSUE THREAD

**Issue by FranciscoKloganB** [GitOpsLovers/nx-biome#3]
I noticed that `nx-biome` plugin generator creates `.biome.json` files. I wonder what is the reason to choose `.biome.json`, instead of the officially mentioned `biome.json` or `biome.jsonc` and what would be the impact of using the official names.

Cheers.

**Comment by mcfdez** [comment]
Hello @FranciscoKloganB 

I have released a new version that makes use of the `biome.json` configuration file as indicated in the official library.

Thanks for the contribution!
