### ISSUE TITLE
Missing feature to pass Biome original flags inline or by config

### ISSUE THREAD

**Issue by devzom** [GitOpsLovers/nx-biome#4]
First, big thanks for creating such a plugin. :) 

the missing feature is that, there's no option to pass a additional arguments/flags for Biome as inline NX args or by the config, such as: 
`--unsafe` 
`--write` and others.

Or it's just a missing plugin docs point?

NX does allow to pass an arguments 
like  
`nx run lib123:biome-lint -- --unsafe`
but doesn't seem that biome command does consume it.

Is it going to be maintained further?

**Comment by mcfdez** [comment]
Hello @devzom 

In the successive versions I will start adding the possibility to add configurations in the plugin that allow the execution of the library with those flags.

Any contribution is welcome! Thank you!

**Comment by mcfdez** [comment]
Hello @devzom 

I have added the possibility to linte the files with --write and --unsafe through the exectuor configuration. These changes are in version 1.5.0 of the plugin.

**Comment by devzom** [comment]
@mcfdez wow, that's pretty fast! Thanks, great info, I'll implement it in project soon :)
